### ISSUE TITLE
Added customizability for Nearby Entities

### ISSUE THREAD

**Issue by BlueLord444** [SilverstoneMC/EntityClearer#12]
Creating a form of white/black list of entities that the nearby entity feature searches for and removes.

See Example: [https://discordapp.com/channels/455919765999976461/872977864029511791/930636497495920640](https://discordapp.com/channels/455919765999976461/872977864029511791/930636497495920640)

**Comment by JasonHorkles** [comment]
Closed via https://github.com/SilverstoneMC/EntityClearer/commit/33b65d63b3b95e470ad6b43be53fe8196d77d1c7
