### ISSUE TITLE
MythicMobs plugin integration

### ISSUE THREAD

**Issue by AllayBreeze** [SilverstoneMC/EntityClearer#17]
The ability to detect MythicMob types and clear them. This will be really useful for servers using custom mobs from the MythicMobs plugin.

For example:

    entities:
      - ExampleMythicMobsInternalName
      - SkeletonKing

The official website of MythicMobs: https://mythiccraft.io/
The wiki page: https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/home
The discord: https://discord.com/invite/K3tqXfT

**Comment by JasonHorkles** [comment]
I'll look into it. Would you be willing to test builds to confirm if they work?

**Comment by AllayBreeze** [comment]
> I'll look into it. Would you be willing to test builds to confirm if they work?

Sure. It's my pleasure.
But it's a pity that I don't know about java programming. Maybe it's needed for you to compile the codes and send me a copy of jar file :)

**Comment by JasonHorkles** [comment]
No worries, I was already planning on compiling it into a jar anyways
I'll try to work on it if I have time within the next week or so

**Comment by JasonHorkles** [comment]
Let me know how https://cdn.discordapp.com/attachments/335445132520194058/1025973066053996626/EntityClearer.jar goes

**Comment by JasonHorkles** [comment]
Config changes [here](https://github.com/SilverstoneMC/EntityClearer/commit/5d4df4f306576202ade6d971d42f42aacf89164c#diff-58cdd3d308ccba6c594e040ff9c065bb11eeb6e30f35ba87694ea45d5ae6096c)

**Comment by AllayBreeze** [comment]
Working on it

**Comment by AllayBreeze** [comment]
It looks pretty good! The clearer is able to distinguish mythicmobs and vanilla mobs, and clear listed mythicmobs correctly.
There's only one small problem found at present that the remove-named configuration appears to ignore mythicmobs. Though remove-named is set to false, whether the name of a mythicmob is configured in mm before or modified by using the name tag, it will always be cleared. Considering that most mythicmobs are named, maybe an independent configuration "remove-named-mythicmobs" can deal with this better. 
Thank you very much for your works in this integration! It really helps me a lot.

**Comment by JasonHorkles** [comment]
Yeah always removing named mmobs was intentional since they always seemed to be named from my testing
I can certainly add a second option though

**Comment by JasonHorkles** [comment]
If that's the only problem found then I'll go ahead and publish the update after I fix that

**Comment by JasonHorkles** [comment]
[Config changes](https://github.com/SilverstoneMC/EntityClearer/commit/e1722f00c5428658e47fcc7d1c1a18654533582b#diff-58cdd3d308ccba6c594e040ff9c065bb11eeb6e30f35ba87694ea45d5ae6096c)
[Jar](https://cdn.discordapp.com/attachments/335445132520194058/1026205142804082688/EntityClearer.jar)
