### ISSUE TITLE
Chunk entity limit

### ISSUE THREAD

**Issue by EagL3-GIT** [SilverstoneMC/EntityClearer#19]
Add something like per-chunk-entity-limit function, to set how many entities 
can be spawned in 1 chunk from the list of entities. (For example: Villager:5)

(Function from ClearLagg)

**Comment by JasonHorkles** [comment]
After thinking about it a bit, this is out of the scope of the plugin. I highly recommend using [FarmControl](https://www.spigotmc.org/resources/farmcontrol-1-15-1-19.86923/) as it can do what you request to a much better degree than I'd ever be able to code
That being said EntityClearer can work along with FarmControl if that's what you so choose
