### ISSUE TITLE
Need Placeholder for Laggtime

### ISSUE THREAD

**Issue by PabloKateee** [SilverstoneMC/EntityClearer#20]
A placeholder for the time when the Clearlagg comes, makes the plugin still perfect, please :)

**Comment by JasonHorkles** [comment]
What would the placeholder be used for? PAPI?

**Comment by PabloKateee** [comment]
if they bring an update of it would be a dream <3 :D

**Comment by JasonHorkles** [comment]
I'll look into it

**Comment by JasonHorkles** [comment]
Closed via 55c3361
