### ISSUE TITLE
Option to disable chat and action bar messages

### ISSUE THREAD

**Issue by MinerCoffee** [SilverstoneMC/EntityClearer#23]
### The suggestion

In the config.yml there should be am option to disable chat messages and  or action bar messages.

### Why it would be useful

 Being double notified is pointless and geyermc users performance is affect.

**Comment by JasonHorkles** [comment]
This is already possible, please read [the comments](https://github.com/SilverstoneMC/EntityClearer/blob/c31479791d883c53efdb45866c0126d5206a441a/src/main/resources/config.yml#L154)
