### ISSUE TITLE
Ability to remove monster entities running inside a mob spawner.

### ISSUE THREAD

**Issue by fadfhkdfga** [SilverstoneMC/EntityClearer#26]
### The suggestion

Ability to remove monster entities running inside a mob spawner.

### Why it would be useful

.

**Comment by JasonHorkles** [comment]
Can you please elaborate? I'm not sure what you mean

**Comment by fadfhkdfga** [comment]
> Can you please elaborate? I'm not sure what you mean

If you look at the basic mob spawner block, you will see a mob spinning around in a cage. This function removes the spinning mob. (i.e. all spawners become empty spawners when run)
If there are a lot of spawners with mobs spinning around in one place, it will cause a huge lag in the client.

**Comment by JasonHorkles** [comment]
I'm not sure that that's something I can control, and would be out of the scope of the plugin regardless, sorry
