### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kybaliion** [SilverstoneMC/EntityClearer#31]
### The suggestion

Adds a way to edit the {TIME} and {TIMELEFT} I want to translate to Portuguese
And if have a way add a possibility to adds gradients in the messages cause my messages is turning so big

### Why it would be useful

Cause have a lot of people for another country that uses your plugin and it's make sense that those people want to edit the language of your plugin and the gradient is useful to made more beautiful

**Comment by JasonHorkles** [comment]
the TIMELEFT placeholder won't be translatable because it's just a number, but the other stuff I can make configurable
