### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by snurre0** [SilverstoneMC/EntityClearer#34]
### The suggestion

I'm not sure what is even possible, but here goes:
It would be handy to be able to see when and how many entities are being removed.

My suggestion is three levels of logging:
- NONE: No logging
- INFO: Log basic information about how many entities were removed, like in the messages in chat
- DEBUG: Log what kind of entities where removed, at what coordinates and how many other entities it counted around it

Potentially splitting the last option in two, and having one where it logs the numbers of each entity, and an even more verbose where we can see coordinates, counts and whatever else there is.

### Why it would be useful

Running a public SMP, you can bet some players will loose entities from us running this plugins, and wanting them back as they were "under the limit" of course, with us having no real proof what wiped their entities and how many they had.
It would be super handy to be able to look up the details, a QoL feature if you will.

**Comment by JasonHorkles** [comment]
There's already a `/ecl debug` command that dumps all the entity info and given how much it can output into logs, that should probably go into its own file. However I can certainly look into the additional customization you requested

**Comment by JasonHorkles** [comment]
However the real question is, is this actually an issue? The odds of the plugin clearing entities it shouldn't when only counting unnamed ones in groups of 15+ by default are pretty low

**Comment by snurre0** [comment]
It's not an issue at all, would just be a nice QoL addition, for both server admins and us nerd wanting to have all the stats ;)
It's not a big deal if it doesn't get added, I guess not a big use case at all.

And I actually missed the debug command for some reason, and damn that was a lof of info, will probably be way too much to actually log continuously.

**Comment by JasonHorkles** [comment]
Yeah lol, it should be easy to add a log for how many entities were cleared at least tho

**Comment by snurre0** [comment]
That would be nice. I have turned off all the messages as I don't like that all our players are seeing them, since there is no permission control for that one(That I could find at least).
And with that turned off, I have no idea if the plugin is doing anything 😅

**Comment by JasonHorkles** [comment]
There were quite a few changes made, so be sure to read the changelogs with the next release ^^
