### ISSUE TITLE
Add Title messages

### ISSUE THREAD

**Issue by ThomasDeStrooper** [SilverstoneMC/EntityClearer#37]
### The suggestion

Can you please add that the cooldown and the complete message is also displayed in tittle screen message?

![Screenshot 2024-12-09 18-25-52](https://github.com/user-attachments/assets/921898b0-a6b8-49c3-81e6-35b7ff5a5f8a)

### Why it would be useful

I really like it and it looks better in my opinion. (you can set it disabled by default for only people that like it can use it)

**Comment by JasonHorkles** [comment]
Why close it?

**Comment by JasonHorkles** [comment]
Completed via fc65f5b
